syms a b c d g h ti ep t ae be dedt q1 q0 p1 tR
% g=a*exp(-b*ti)+c*exp(-d*ti)+g*exp(-h*ti)
g=a*exp(-b*(t-ti))+c*exp(-d*(t-ti))+g*exp(-h*(t-ti))

sigep=ae*(exp(be*ep)-1)
dsde=ae*be*exp(be*dedt*ti)
sigramp=dedt*int(g*dsde,ti,0,t)
sigrelax=sigramp-dedt*int(g*dsde,ti,tR,t)
% sig=-(a*ae*be*dedt*exp(be*ep)*(exp(-b*t) - 1))/b -...
    % (ae*be*c*dedt*exp(be*ep)*(exp(-d*t) - 1))/d - ...
    % (ae*be*dedt*g*exp(be*ep)*(exp(-h*t) - 1))/h

y3es = q1/p1*exp(-(t-ti)/p1) + q0*(1-exp(-(t-ti)/p1));
sig3es=dedt*(int(y3es,ti,0,t)-int(y3es,ti,tR,t));

sigrelaxfull=- dedt*(a*ae*be*(exp(be*dedt*t)/(b + be*dedt) -...
    (exp(be*dedt*data.time(s0_loc)).*exp(-b*t)*exp(b*data.time(s0_loc)))/(b + be*dedt)) +...
                     ae*be*c*(exp(be*dedt*t)/(d + be*dedt) -...
    (exp(be*dedt*data.time(s0_loc)).*exp(-d*t)*exp(d*data.time(s0_loc)))/(d + be*dedt)) +...
                     ae*be*g*(exp(be*dedt*t)/(h + be*dedt) - ...
    (exp(be*dedt*data.time(s0_loc))*exp(-h*t).*exp(h*data.time(s0_loc)))/(h + be*dedt))) -...
    ...
    dedt*(a*ae*be*(exp(-b*t)/(b + be*dedt) -...
    exp(be*dedt*t)/(b + be*dedt)) +...
    ae*be*c*(exp(-d*t)/(d + be*dedt) ...
    - exp(be*dedt*t)/(d + be*dedt)) +...
    ae*be*g*(exp(-h*t)/(h + be*dedt) -...
    exp(be*dedt*t)/(h + be*dedt)));